### PR TITLE
fix: `useChannel` hook with `ChannelOptions` throws error

### LINKED ISSUE #42: useChannel hook with `ChannelOptions` throws error when component re-renders
This is because ably-js `channels.get` throws an error when called on the same channel twice with an options param. The solution to this should be to wrap the `channels.get` call in a `useMemo`.

### PR DESCRIPTION
**Pull request by ttypic**
Resolves #42  

Jira links:
* [SDK-3751] 

Optimized get channel invocation with memoization to prevent repeated calls during re-renders, preventing errors caused by redundant invocations.

[SDK-3751]: https://ably.atlassian.net/browse/SDK-3751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: src/hooks/useChannel.ts [hunk 1]
```diff
@@ -23,24 +23,20 @@ export function useChannel(
...
-            : ably.channels.get(
-                  channelName,
-                  channelNameOrNameAndOptions.options
-              );
+    const { channelName } = channelOptions;
+
+    const channel = useMemo(
+        () => ably.channels.get(channelName, channelOptions.options),
+        // ignoring options change
+        [channelName]
```
Comment (owenpearson) [inline src/hooks/useChannel.ts:38]: I realise I didn't capture this in the issue description but it might be worth putting the options in a ref and using `useEffect` to call `channel.setOptions` if they change?

**Review by owenpearson — CHANGES_REQUESTED** [review]
Looks good! One suggestion though:L

File: src/hooks/useChannel.ts (hunk 1 above)
Comment (ttypic) [reply src/hooks/useChannel.ts:38]: It's great idea!

**Review by owenpearson — APPROVED** [review]
LGTM, nice 🙂
